"""Initial migration1.

Revision ID: 8c8154096d3b
Revises: eb1d7834013a
Create Date: 2022-08-17 12:10:56.239435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8154096d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_structure', sa.Column('population', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_structure', 'population')
    # ### end Alembic commands ###
